FROM openjdk:11-jdk-slim
RUN mkdir /opt/product-service
WORKDIR /opt/product-service
COPY ./build/libs/product-service.jar /opt/product-service/product-service.jar
CMD ["java","-jar","product-service.jar"]